Consume PF4 pagination from core
theforeman/foreman_leapp pull request #110
Opened 2022-01-18 15:34 UTC by stejskalleos

2022-01-19 15:17 UTC, ezr-ondrej requested changes
I did not check, but the properties passed to Pagination here seems same as in REX, so I believe we have the same issues as mentioned in https://github.com/theforeman/foreman_remote_execution/pull/682#pullrequestreview-856017528

2022-01-19 15:26 UTC, stejskalleos commented
Waiting for https://github.com/theforeman/foreman_remote_execution/pull/682

2022-01-24 11:46 UTC, stejskalleos commented
Updated, removed unused props and fixed `per_page` args

2022-01-24 16:57 UTC, Ron-Lavi reviewed
Overall looks great, I don't have a pre-upgrade report so couldn't actually test it,
@ezr-ondrej do you have the setup?

2022-01-24 16:57 UTC, Ron-Lavi commented on webpack/components/PreupgradeReportsList/index.js
> +        // dropdownButtonId="preupgrade-report-entries-pagination-dropdown"
the commented lines can be removed

2022-01-25 08:43 UTC, stejskalleos commented
> Overall looks great, I don't have a pre-upgrade report so couldn't actually test it

You can generate report pretty simple:

Install Leapp on CentOS machine:
```
yum install -y yum-utils
yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/g/oamg/leapp/repo/epel-7/group_oamg-leapp-epel-7.repo
yum install leapp
```
run preupgrade job in Foreman
If you don't have much records in report, you can add some more:
```
bundle exec rails console
100.times { PreupgradeReportEntry.first.dup.save }
```

2022-01-30 09:13 UTC, Ron-Lavi commented
Having some issues on my machine, @ezr-ondrej mind taking a look?

2022-01-30 11:57 UTC, ezr-ondrej approved these changes
It was quite hard to setup (leapp is not very straight forward to install).
It could be beneficial to have some script to feed the DB with dummy records for ppl to test out the plugin without having the production setup working. Or at least a documentation on how to set it up :)
Tho this works :+1:  Thanks @stejskalleos

2022-01-30 11:58 UTC, ezr-ondrej commented
We need someone with merge permissions tho.

2022-01-31 16:23 UTC, Ron-Lavi commented
Maybe @adamruzicka for the rescue? :)

2022-02-01 07:53 UTC, adamruzicka commented
Shouldn't this also bump the required foreman version in engine.rb?

2022-02-01 08:11 UTC, stejskalleos commented
> Shouldn't this also bump the required foreman version in engine.rb?

Yop, updated to `3.2`

2022-02-01 09:14 UTC, adamruzicka approved these changes
LGTM

2022-02-01 09:14 UTC, merged

2022-02-01 09:15 UTC, adamruzicka commented
Thank you everyone!