Add translations for pt_BR, zh_CN and zh_TW
theforeman/foreman_leapp pull request #129
Opened 2023-07-25 07:53 UTC by stejskalleos

2023-07-25 10:10 UTC, adamruzicka commented on locale/action_names.rb
> +_("Deliver notifications about long running tasks")
That's from tasks, https://github.com/theforeman/foreman-tasks/blob/master/app/lib/actions/check_long_running_tasks.rb#L42 and https://github.com/theforeman/foreman-tasks/blob/master/app/lib/actions/deliver_long_running_tasks_notification.rb#L19

2023-07-25 10:42 UTC, stejskalleos commented on locale/action_names.rb
> +_("Deliver notifications about long running tasks")
This is how I updated the translations:

* `mkdir -p locale/{en,fr,ja,zh_CN,zh_TW,pt_BR}`
* `make -C locale tx-update` (In plugin dir)
From foreman:
Edit gem file (only one plugin enabled)
* `bundle;be rails db:drop;be rails db:create;be rails db:migrate`
* `P="foreman_leapp";be rake "plugin:gettext[$P]" && be rake "plugin:po_to_json[$P]"`
From plugin dir:
* `make -C locale mo-files`

2023-07-25 10:42 UTC, stejskalleos commented on locale/action_names.rb
> +_("Deliver notifications about long running tasks")
No plugin except foreman leapp is enabled

2023-07-25 10:47 UTC, adamruzicka commented on locale/action_names.rb
> +_("Deliver notifications about long running tasks")
> No plugin except foreman leapp is enabled

leapp depends on rex and ansible, both depend on tasks.

2023-07-25 11:59 UTC, ekohl commented on locale/action_names.rb
> +_("Deliver notifications about long running tasks")
Ah ok, then it makes sense. This does highlight that it becomes more important to somehow be able to filter those tasks out.

2023-08-02 09:16 UTC, stejskalleos commented on locale/action_names.rb
> +_("Deliver notifications about long running tasks")
SO can we merge?

2023-08-02 09:21 UTC, ekohl requested changes
It looks like Japanese is missing, which does have translations in Transifex. Perhaps that was fixed when I resynced with the proper encoding. Mind pulling again to make sure?

2023-08-03 07:51 UTC, stejskalleos commented
Updated the strings but it looks like Japanese translation is still empty

2023-11-27 08:53 UTC, closed without merging